### ISSUE TITLE
no provider for ContentsDirective when using contentsLink

### ISSUE THREAD

**Issue by gagandeepgill** [zurfyx/angular-contents#3]
I get this error while using contentsLink, I have imported your package correctly. All the other directives work fine but this one is giving me issues.

![capture](https://user-images.githubusercontent.com/8551508/34733937-15826ef6-f538-11e7-85ca-fa24e0829c6e.PNG)

**Comment by zurfyx** [comment]
Hi gagandeepgill,

Is this a specific extension? I'd like to try it out. My vscode doesn't notify me of such errors.

I find it strange that you get a provider error when this library is fully about directives. I have just had a look at the implementation of this particular directive and maybe it might be because of rxjs missing, which I forgot to add to peer dependencies. From v2.0.1 you'll be warned to install `rxjs ^5.5.2`.

Do you get any console error too that gives more information than this? Also, if you can get a sample uploaded somewhere I might be able to find out more about your particular issue.

**Comment by gagandeepgill** [comment]
![image](https://user-images.githubusercontent.com/8551508/34793652-246299b8-f61a-11e7-86b3-8ac81d47b903.png)

this is what I get from console in chrome and I also have rxjs it up to date.

![image](https://user-images.githubusercontent.com/8551508/34793733-60eb9920-f61a-11e7-90fe-45c79eafdbc4.png)

**Comment by zurfyx** [comment]
That's very weird. I'd like to see a full working version to test it myself.

Does your `@Module` and `@Component` look like the ones in the example?

Your component's module (where you are using it), should have the single `ContentsModule` import, component should have nothing special.

YourModule.module.ts

```
import { ContentsModule } from 'angular-contents';

@NgModule({
  imports: [
    ContentsModule, // Importing this single module will add all library directives that are required.
  ],
  declarations: [
		// Angular Contents requires no declarations.
  ],
  providers: [], // Angular Contents has no providers.
})
export class YourModuleModule { }
```

You've probably done already, but I encourage you to have a second in-depth look at the [example code](https://github.com/zurfyx/angular-contents/tree/master/example/app) and see if there's something different in your project. The demo code is the one that is [running on GitHub Pages](https://zurfyx.github.io/angular-contents), which is working fine. So if you do just like in the demo it should work well.

**Comment by gagandeepgill** [comment]
I solved the problem, I was using another module for routing apps and I had to import your package in there. I wouldn't have looked into it if you haven't told me to look at my modules again.

Thanks for the help!

**Comment by zurfyx** [comment]
I'm glad that you managed to solve it! Happy coding :D
